"""Initial schema for BO-MCP database.

This migration creates all tables for the Bayesian Optimization MCP service:
- users: User accounts with API key authentication
- campaign_specs: Immutable optimization problem specifications
- campaigns: Active optimization campaigns with state tracking
- suggestions: Parameter suggestions generated by the BO engine
- results: Experimental results submitted by users

Revision ID: 001_initial
Revises: None
Create Date: 2025-01-16 00:00:00.000000
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Create initial database schema."""
    # Users table
    op.create_table(
        "users",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("email", sa.String(255), nullable=False, unique=True),
        sa.Column("api_key_hash", sa.String(255), nullable=False),
        sa.Column("is_active", sa.Boolean(), default=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_active_at", sa.DateTime(), nullable=True),
    )
    op.create_index("ix_users_email", "users", ["email"])
    op.create_index("ix_users_api_key_hash", "users", ["api_key_hash"])

    # Campaign specifications table
    op.create_table(
        "campaign_specs",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("description", sa.Text(), default="", nullable=False),
        sa.Column("parameters_json", sa.Text(), nullable=False),
        sa.Column("objectives_json", sa.Text(), nullable=False),
        sa.Column("constraints_json", sa.Text(), default="[]", nullable=False),
        sa.Column("batch_size", sa.Integer(), default=1, nullable=False),
        sa.Column("max_iterations", sa.Integer(), nullable=True),
        sa.Column("initial_design_size", sa.Integer(), nullable=True),
        sa.Column("random_seed", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
    )

    # Campaigns table
    op.create_table(
        "campaigns",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column(
            "spec_id",
            sa.String(36),
            sa.ForeignKey("campaign_specs.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column(
            "owner_id",
            sa.String(36),
            sa.ForeignKey("users.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("CREATED", "RUNNING", "PAUSED", "COMPLETED", "FAILED", name="campaignstatus"),
            default="CREATED",
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), default=1, nullable=False),
        sa.Column("iteration", sa.Integer(), default=0, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("turbo_state_json", sa.Text(), nullable=True),
        sa.Column("hypervolume_history_json", sa.Text(), default="[]", nullable=False),
    )
    op.create_index("ix_campaigns_owner_id", "campaigns", ["owner_id"])
    op.create_index("ix_campaigns_status", "campaigns", ["status"])

    # Suggestions table
    op.create_table(
        "suggestions",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column(
            "campaign_id",
            sa.String(36),
            sa.ForeignKey("campaigns.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("parameter_values_json", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "EVALUATED", "FAILED", "CANCELLED", name="suggestionstatus"),
            default="PENDING",
            nullable=False,
        ),
        sa.Column("provenance_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
    )
    op.create_index("ix_suggestions_campaign_id", "suggestions", ["campaign_id"])
    op.create_index("ix_suggestions_status", "suggestions", ["status"])

    # Results table
    op.create_table(
        "results",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column(
            "campaign_id",
            sa.String(36),
            sa.ForeignKey("campaigns.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "suggestion_id",
            sa.String(36),
            sa.ForeignKey("suggestions.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("parameter_values_json", sa.Text(), nullable=False),
        sa.Column("objective_values_json", sa.Text(), nullable=False),
        sa.Column(
            "source",
            sa.Enum("API", "MCP", "MANUAL", "HISTORICAL", name="resultsource"),
            nullable=False,
        ),
        sa.Column("submitted_by", sa.String(36), nullable=False),
        sa.Column("metadata_json", sa.Text(), default="{}", nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
    )
    op.create_index("ix_results_campaign_id", "results", ["campaign_id"])
    op.create_index("ix_results_suggestion_id", "results", ["suggestion_id"])


def downgrade() -> None:
    """Drop all tables in reverse order."""
    # Drop tables (reverse order of creation due to foreign keys)
    op.drop_table("results")
    op.drop_table("suggestions")
    op.drop_table("campaigns")
    op.drop_table("campaign_specs")
    op.drop_table("users")

    # Drop enum types (PostgreSQL only)
    op.execute("DROP TYPE IF EXISTS resultsource")
    op.execute("DROP TYPE IF EXISTS suggestionstatus")
    op.execute("DROP TYPE IF EXISTS campaignstatus")
